# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageclass',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='class_name',
            new_name='category',
        ),
    ]
