# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170425_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
