# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170425_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
